name: Hardhat Hospitality
favicon: null
layout_spectrum: 0.33729
typography_spectrum: 0.39268623921088874
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e5e5'
    - '#2b2b2b'
    - '#c5c5c5'
    - '#989898'
    - '#686868'
  brandStrength: 0.633471553446725
  lightness: 0.4817351067904383
  saturation: 0.6456577498465776
  rhythmicContrast: 0.007992865284904838
purpose: []
